### ISSUE TITLE
Not able to create test merchant

### ISSUE THREAD

**Issue by commercex** [poynt/PoyntSamples#21]
I am trying to create a test merchant.
I am getting the below error.

INVALID_PARAMETER: Parameter provided is invalid. Every store must have an externalStoreId (aka MID).

following  this tutorial https://poynt.github.io/developer/tut/activate-poynt-terminal.html

**Comment by charlesfeng** [comment]
Hi, so sorry about that! We are deploying a fix now -- I'll post here again in ~15min when I've verified it works.

**Comment by charlesfeng** [comment]
Hi @commercex, you should be able to create test merchants now. Please try again and let me know!

**Comment by commercex** [comment]
It worked now.

Thanks for the quick fix :+1:

**Comment by commercex** [comment]
When i scan the qrcode the poynt terminal show the device is activated.
After that i get this error "cannot inject keys plesea verify whether your device is registered with poynt".

The online dashboard show the terminal is activate but i am back to activation screen.

**Comment by dsnatochy** [comment]
@commercex what is your device serial #?

**Comment by commercex** [comment]
I haven't enabled developer mode .
Is that mandatory ? 
https://poynt.github.io/developer/tut/developer-mode.html

**Comment by commercex** [comment]
Device Serial No:
P61SWD098GS005333

**Comment by mansilladev** [comment]
Enabling developer mode isn't required for activation and using the terminal; however, in order to use **adb** (Android Debug Bridge), which is helpful for checking out the device logs and side-loading your apps, you will need to enable developer mode.

**Comment by commercex** [comment]
So whats the reason for this error ?
**"cannot inject keys plesea verify whether your device is registered with poynt".**

**Comment by dsnatochy** [comment]
The activation issue was resolved over email.

**Comment by shamnaTechie** [comment]
where is this developer mode option in poynt.
